# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a77e10c09c542f46bb6023cd2eabffb414f40666acf599c665d539ba3cdfe113babb03c07dfe2acfed52342c8321b9c97de42be9546028b5696dafb18538ad73

test:
  secret_key_base: 6cbed22c4312541981da53e635cc59cb779d0d2143053ccc1c824693f30bc1a64091ba4c6f30fb66822f3c99da5c20a6cb2c127b6bb8f02f56acaaab369f0c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
